abstract: Use other catalog formats in Maketext
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: mit
name: Locale-Maketext-Lexicon
no_index: 
  directory: 
    - inc
    - t
requires: 
  Locale::Maketext: 0.01
  perl: 5.004
version: 0.61
