name: Locale-Maketext-Lexicon
version: 0.53
abstract: Use other catalog formats in Maketext
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  Test::More: 0.01
  Locale::Maketext: 0.01
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
