--- 
abstract: Use other catalog formats in Maketext
author: 
  - Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: MIT
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Locale-Maketext-Lexicon
no_index: 
  directory: 
    - inc
    - t
requires: 
  Locale::Maketext: 0.01
  perl: 5.004
version: 0.67
