abstract: Use other catalog formats in Maketext
author: Audrey Tang <audreyt@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Locale-Maketext-Lexicon
no_index: 
  directory: 
    - inc
    - t
requires: 
  Locale::Maketext: 0.01
  Test::More: 0.01
version: 0.56
