#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Locale-Maketext-Lexicon
version:      0.27
version_from: lib/Locale/Maketext/Lexicon.pm
installdirs:  site
requires:
    Test::More:                    0.01
    Regexp::Common:                0.01
    Pod::Usage:                    0.01
    Locale::Maketext:              0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_04
